import "../styles/globals.css";
import Layout from "../components/layout/Layout";
import { SessionProvider } from "next-auth/react";
import Head from "next/head";
import { AuthContextProvider } from "../store/auth-context";
function MyApp({ Component, pageProps: { session, ...pageProps } }) {
  return (
    <SessionProvider session={session} refetchInterval={5 * 60}>
      <AuthContextProvider>
       <Head>
        <title>Summer Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
      </AuthContextProvider>
    </SessionProvider>
  );
}

export default MyApp;


